python_manylinux_wheel:
  image: quay.io/pypa/manylinux2014_x86_64
  stage: build
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - export PATH=$PATH:/opt/python/cp310-cp310/bin/
    - source /opt/rh/devtoolset-10/enable
    - pip install conan ninja
    - mkdir build
    - cd build
    - cmake ../libket -GNinja -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_STANDARD=17
    - ninja 
    - python3.10 setup.py sdist
  artifacts:
    paths:
      - dist
