image: registry.gitlab.com/quantum-ket/ket

stages:
  - build
  - deploy

wheelhouse:
  stage: build
  script:
    - source scl_source enable devtoolset-10 || true
    - source scl_source enable rh-python38 || true
    - source scl_source enable rh-git227 || true
    - source /root/.cargo/env
    - ./util/make_libs.sh
    - ./util/make_wheel.sh
  artifacts:
    paths:
      - wheelhouse

PyPI:
  stage: deploy
  script:
    - source scl_source enable rh-python38 || true
    - TWINE_PASSWORD=${CI_JOB_TOKEN} TWINE_USERNAME=gitlab-ci-token python -m twine upload --repository-url ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi wheelhouse/*
  only:
    - master
