sdist:
  image: ubuntu:20.04
  stage: build
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - apt update
    - DEBIAN_FRONTEND=noninteractive TZ=America/Sao_Paulo apt install python3-pip cmake ninja-build g++ -y
    - pip install conan
    - mkdir build
    - cd build
    - cmake ../libket -GNinja -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_STANDARD=17
    - ninja 
    - cd ..
    - python3.10 setup.py sdist
  artifacts:
    paths:
      - dist
