sdist:
  image: centos:7
  stage: build
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - yum install centos-release-scl -y
    - yum install devtoolset-8-toolchain rh-python38 -y
    - source scl_source enable devtoolset-8 || true
    - source scl_source enable rh-python38 || true
    - pip install setuptools conan cmake ninja -U
    - mkdir build
    - cd build
    - cmake ../libket -GNinja -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_STANDARD=17
    - ninja 
    - cd ..
    - python setup.py sdist
  artifacts:
    paths:
      - dist
