wheelhouse:
  image: centos:7
  stage: build
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - yum install centos-release-scl -y
    - yum install devtoolset-11-gcc rh-python38 -y
    - source scl_source enable devtoolset-11 || true
    - source scl_source enable rh-python38 || true
    - pip install build auditwheel setuptools patchelf -U
    - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
    - source $HOME/.cargo/env
    - cd libs
    - cargo build --release
    - cd ..
    - python -m build
    - auditwheel repair --plat manylinux_2_17_x86_64 dist/ket_lang-*-py3-none-any.whl
  artifacts:
    paths:
      - wheelhouse
