stages:
  - build
  - audit
  - test
  - deploy

variables:
  GIT_SUBMODULE_STRATEGY: recursive

Compile Rust Libs:
  image: rust:1.65-slim-buster
  stage: build
  script:
    - cargo build --release --manifest-path src/ket/clib/libs/libket/Cargo.toml
    - cargo build --release --manifest-path src/ket/clib/libs/kbw/Cargo.toml
    - mv src/ket/clib/libs/libket/target/release/libket.so src/ket/clib/libs/libket.so
    - mv src/ket/clib/libs/kbw/target/release/libkbw.so src/ket/clib/libs/libkbw.so
  artifacts:
    paths:
      - src/ket/clib/libs/libket.so
      - src/ket/clib/libs/libkbw.so

Package Source Code:
  image: python:3-slim
  stage: build
  script:
    - pip install build
    - python -m build -s
  artifacts:
    paths:
      - dist/ket-lang*.tar.gz

Package Wheel:
  image: python:3-slim
  stage: audit
  script:
    - pip install build auditwheel patchelf
    - rm -rf src/ket/clib/libs/libket src/ket/clib/libs/kbw.so
    - python -m build -w
    - python -m auditwheel repair --plat manylinux_2_28_x86_64 dist/ket_lang*.whl
  artifacts:
    paths:
      - wheelhouse/ket_lang*.whl

Test Wheel:
  image: python:3.7-slim
  stage: test
  script:
    - pip install wheelhouse/ket_lang*.whl flake8 pylint pytest pytest-cov
    - python -m flake8 src/ket
    - python -m pylint --disable=C0114 src/ket
    - python -m pytest

PyPI Upload:
  image: python:alpine3.16
  stage: deploy
  script:
    - pip install twine
    - python -m twine upload wheelhouse/*
    - python -m twine upload dist/ket-lang*.tar.gz
  only:
    - master

sast:
  stage: test
include:
  - template: Security/SAST.gitlab-ci.yml
