#image: ubuntu:20.04
#
#before_script:
#  - ln -snf /usr/share/zoneinfo/America/Los_Angeles /etc/localtime
#  - apt-get update -y 
#  - apt-get install -y 
#      cmake 
#      desktop-file-utils
#      fakeroot
#      fuse
#      g++ 
#      gcc 
#      git
#      gtk-update-icon-cache
#      libgdk-pixbuf2.0-dev 
#      libgmp-dev
#      libssl-dev 
#      make 
#      ninja-build 
#      patchelf
#      pkg-config
#      python3
#      python3-pip 
#      python3-setuptools
#      sed
#      swig 
#      unzip
#      uuid-dev
#      wget
#  - wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage -O /usr/bin/appimagetool.AppImage
#  - chmod +x /usr/bin/appimagetool.AppImage
#  - /usr/bin/appimagetool.AppImage --appimage-extract
#  - mv squashfs-root /usr/bin/appimage.AppDir
#  - ln -s /usr/bin/appimage.AppDir/AppRun /usr/bin/appimagetool
#  - pip3 install appimage-builder
#
#appimage:
#  script:
#    - git submodule update --init --recursive --remote
#    - sed 's/VERSION/"'$(git rev-parse --short HEAD)'"/' AppImageBuilder.yml.in > AppImageBuilder.yml
#    - appimage-builder --skip-test
#  artifacts:
#    paths:
#      - ./*.AppImage
#  only:
#    - master
manylinux:
  image: python:3.8
  services:
    - name: docker:dind
      entrypoint: ["env", "-u", "DOCKER_HOST"]
      command: ["dockerd-entrypoint.sh"]
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
    CIBW_PROJECT_REQUIRES_PYTHON: ">=3.8"
  script:
    - curl -sSL https://get.docker.com/ | sh
    - python -m pip install cibuildwheel==1.12.0
    - git submodule update --init --recursive --remote
    - make
    - cibuildwheel --output-dir python_pkg
  artifacts:
    paths:
      - python_pkg/