wheelhouse:
  image: registry.gitlab.com/quantum-ket/ket
  stage: build
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  script:
    - source scl_source enable devtoolset-11 || true
    - source scl_source enable rh-python38 || true
    - cd libs
    - cargo build --release
    - cd ..
    - python -m build
    - auditwheel repair --plat manylinux_2_17_x86_64 dist/ket_lang-*-py3-none-any.whl
  artifacts:
    paths:
      - wheelhouse
