image: registry.gitlab.com/quantum-ket/devcontainer

stages:
  - build
  - test
  - deploy

Build:
  stage: build
  script:
    - source scl_source enable devtoolset-7 || true
    - source scl_source enable rh-python38 || true
    - source scl_source enable rh-git227 || true
    - source /home/quantum/.cargo/env
    - python setup.py sdist
    - python setup.py bdist_wheel
    - auditwheel repair --plat manylinux_2_17_x86_64 dist/ket_lang*.whl
  artifacts:
    paths:
      - wheelhouse/ket_lang*.whl
      - dist/ket-lang*.tar.gz

Test:
  stage: test
  script:
    - source scl_source enable rh-git227 || true
    - source scl_source enable rh-python38 || true
    - pip install wheelhouse/ket_lang*.whl --user
    - flake8 src/ket
    - pylint --disable=C0114 src/ket
    - pytest

PyPI:
  stage: deploy
  script:
    - source scl_source enable rh-python38 || true
    - python -m twine upload wheelhouse/*
    - python -m twine upload dist/ket-lang*.tar.gz
  only:
    - master

sast:
  stage: test
include:
  - template: Security/SAST.gitlab-ci.yml
