name: ket
title: Ket quantum programming
version: git
grade: devel
license: MIT
summary: The Ket quantum programming language interpreter
description: Source code available at https://gitlab.com/quantum-ket/ket

base: core20
confinement: strict

parts:
  python:
    plugin: python
    python-packages: 
      - conan 
      - ast_decompiler
    stage-packages:
      - python3.8-minimal
      - libpython3.8
    override-stage:
      snapcraftctl stage &&
      rm bin/python3 &&
      ln -s ../usr/bin/python3.8 bin/python3 

  libket:
    plugin: cmake
    source: .
    build-packages: 
      - pkg-config
      - uuid-dev
      - swig
      - curl
      - make
      - default-jre
      - unzip
      - g++
      - gcc
    build-environment:
      - PATH : $PATH:/root/parts/python/install/bin
      - PYTHONPATH: /root/parts/python/install/lib/python3.8/site-packages
    cmake-parameters:
      - -DPYTHON_PACKAGES=/lib/python3.8/site-packages
      - -DSNAP=1
    after:
      - python
  
apps:
  ket:
    command: bin/python3 -m keti
    plugs:
      - home
    environment:
      LC_ALL: C.UTF-8
      LANG: C.UTF-8
