name: ket
title: Ket quantum programming
version: '0.1'
grade: devel
license: MIT
summary: The Ket quantum programming language interpreter
description: Source code available at https://gitlab.com/quantum-ket/ket

base: core20
confinement: strict

parts:
  py:
    plugin: python
    python-packages: 
      - conan 
      - ast_decompiler
    build-packages: 
      - python3-wheel
    stage-packages:
      - python3
      - libpython3.8

  libket:
    plugin: cmake
    source: .
    build-packages: 
      - pkg-config
      - uuid-dev
      - swig
      - make
      - default-jre
      - g++
      - gcc
    build-environment: 
      - PATH: /root/parts/python/install/bin:$PATH
      - PYTHONPATH: /root/parts/python/install/lib/python3.8/site-packages
    cmake-parameters:
      - -DPYTHON_PACKAGES=/lib/python3/site-packages
      - -DSNAP=1
    after:
      - py
  
apps:
  ket:
    command: usr/bin/python3.8 -m keti
    plugs:
      - home
    environment:
      LC_ALL: C.UTF-8
      LANG: C.UTF-8
