name: ket
title: Ket quantum programming
summary: Quantum programming language
description: |
  Ket is a Python-embedded language for hybridity classical-quantum programming.

  The Ket Bitwise simulator is necessary to simulate quantum execution. Before
  installing ket, you need to install kbw:

      sudo snap install kbw --edge

  Usage:

      $ ket input.ket -h
      Ket program options:
        -h [ --help ]          Show this information
        -o [ --out ]           KQASM output file
        -s [ --kbw ]  (=::1)   Quantum execution (KBW) address
        -p [ --port ]  (=4242) Quantum execution (KBW) port address
        --no-execute           Does not execute quantum code, measurements return 0

  This project is part of the Ket Quantum Programming framework that also
  features:

  * The C++ quantum programming library Libket.
  * The Ket Bitwise Simulator for quantum computation.

  See the documentation for more information http://quantum-ket.gitlab.io.
  
icon: icon/ket.svg

license: Apache-2.0

version: git
grade: devel

base: core20
confinement: strict

parts:
  snapcraft-preload:
    source: https://github.com/sergiusens/snapcraft-preload.git
    plugin: cmake
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/
    build-packages:
      - on amd64:
        - gcc-multilib
        - g++-multilib
    stage-packages:
      - on amd64:
        - lib32stdc++6

  ket:
    plugin: python
    source: .
    python-packages: 
      - conan
      - distro==1.1.0
      - ninja 
      - scikit-build
    build-packages:
      - cmake
      - g++
      - gcc
      - libgmp-dev
      - libssl-dev
      - make
      - ninja-build
      - pkg-config
      - swig
      - uuid-dev
    override-build:
      make &&
      snapcraftctl build
    stage-packages:
      - libpython3.8-dev
      - python3-distutils
      - python3.8-minimal
    filesets:
      ket-files:
        - lib/python3.8/site-packages/ket*
      python-files:
        - usr/lib/python3.8/
        - usr/bin/python3.8
        - usr/lib/x86_64-linux-gnu/libpython3.8.so*
    prime:
      - $ket-files
      - $python-files
    after: 
      - snapcraft-preload
 
apps:
  ket:
    command: bin/snapcraft-preload $SNAP/usr/bin/python3.8 -m ket
    plugs:
      - home
      - network
    environment:
      LC_ALL: C.UTF-8
      LANG: C.UTF-8
      PYTHONPATH: $SNAP/lib/python3.8/site-packages:$SNAP_USER_COMMON/lib/python3.8/site-packages
