name: ket
title: Ket quantum programming
summary: Quantum programming language
description: |
  Ket is a Python-embedded classical-quantum programming language for dynamic
  interaction between classical and quantum computers.

  The Ket Bitwise simulator is necessary to simulate quantum execution. Before
  installing ket, you need to install kbw:

      sudo snap install kbw --edge

  Usage:

      $ ket <input.ket> -h
      Ket program options:
        -h [ --help ]         Show this information
        -s [ --seed ]         Pseudo random number generator seed
        -o [ --out ]          kqasm output file
        -b [ --kbw ]          Path to the Ket Bitwise simulator
        -p [ --plugin ]       Ket Bitwise plugin directory path
        --no-execute          Do not execute the quantum code, measuments will return
                              0

  This project is part of the Ket Quantum Programming framework that also
  features:

  * The C++ quantum programming library Libket.
  * The Ket Bitwise Simulator for quantum computation.

  See the documentation for more information http://ket.readthedocs.io.

icon: docs/source/img/logo11.svg

license: MIT

version: git
grade: devel

base: core20
confinement: strict

parts:
  python:
    plugin: python
    source: .
    python-packages: 
      - distro==1.1.0
      - scikit-build
      - conan
    build-packages:
      - cmake
      - g++
      - gcc
      - libssl-dev
      - make
      - ninja-build
      - pkg-config
      - swig
      - uuid-dev
    override-build:
      make &&
      snapcraftctl build
    stage-packages:
      - python3.8-minimal
      - libpython3.8-dev
    filesets:
      ket-files:
        - lib/python3.8/site-packages/ket*
      python-files:
        - usr/lib/python3.8/
        - usr/bin/python3.8
        - usr/lib/x86_64-linux-gnu/libpython3.8.so*
    prime:
      - $ket-files
      - $python-files
 
plugs:
  kbw:
    interface: content
    content: executables
    target: $SNAP/kbw
    default-provider: kbw
    
  plugins:
    interface: content
    content: libraries
    target: $SNAP/usr/lib/kbw
    default-provider: kbw

apps:
  ket:
    command: usr/bin/python3.8 -m ket
    plugs:
      - home
    environment:
      LC_ALL: C.UTF-8
      LANG: C.UTF-8
      PATH: $SNAP/kbw:$PATH
      PYTHONPATH: $SNAP/lib/python3.8/site-packages
