name: ket
title: Ket quantum programming
summary: Quantum programming language
description: |
  Ket is a Python-embedded classical-quantum programming language for dynamic
  interaction between classical and quantum computers.

  The Ket Bitwise simulator is necessary to simulate quantum execution. Before
  installing ket, you need to install kbw:

      sudo snap install kbw --edge

  Usage:

      $ ket input.ket -h
      Ket program options:
        -h [ --help ]              Show this information
        -o [ --out ]               KQASM output file
        -s [ --kbw ]  (=127.0.1.1) Quantum execution (KBW) address
        -p [ --port ]  (=4242)     Quantum execution (KBW) port address
        --no-execute               Does not execute the quantum code, measuments 
                                   return 0

  This project is part of the Ket Quantum Programming framework that also
  features:

  * The C++ quantum programming library Libket.
  * The Ket Bitwise Simulator for quantum computation.

  See the documentation for more information http://quantum-ket.gitlab.io.

icon: icon/ket.svg

license: MIT

version: git
grade: devel

base: core20
confinement: strict

parts:
  python:
    plugin: python
    source: .
    python-packages: 
      - conan
      - distro==1.1.0
      - ninja 
      - scikit-build
    build-packages:
      - cmake
      - g++
      - gcc
      - libssl-dev
      - make
      - ninja-build
      - pkg-config
      - swig
      - uuid-dev
    override-build:
      make &&
      snapcraftctl build
    stage-packages:
      - python3-distutils
      - python3.8-minimal
      - libpython3.8-dev
    filesets:
      ket-files:
        - lib/python3.8/site-packages/ket*
      python-files:
        - usr/lib/python3.8/
        - usr/bin/python3.8
        - usr/lib/x86_64-linux-gnu/libpython3.8.so*
    prime:
      - $ket-files
      - $python-files
 
apps:
  ket:
    command: usr/bin/python3.8 -m ket
    plugs:
      - home
      - network
    environment:
      LC_ALL: C.UTF-8
      LANG: C.UTF-8
      PYTHONPATH: $SNAP/lib/python3.8/site-packages:$SNAP_USER_COMMON/lib/python3.8/site-packages
