name: ket
title: Ket quantum programming
version: git
grade: devel
license: MIT
summary: The Ket quantum programming language interpreter
description: For more information see the documentation at http://ket.readthedocs.io

base: core20
confinement: strict

parts:
  python:
    plugin: python
    python-packages: 
      - distro==1.1.0
      - scikit-build
      - conan
    stage-packages:
      - python3.8-minimal
      - libpython3.8
    override-stage:
      snapcraftctl stage &&
      rm bin/python3 &&
      ln -s ../usr/bin/python3.8 bin/python3 
    source: .
    build-packages:
      - cmake
      - swig
      - ninja-build
      - pkg-config
      - uuid-dev
      - g++
      - gcc

plugs:
  kbw:
    interface: content
    content: executables
    target: $SNAP/kbw
    default-provider: kbw
    
  plugins:
    interface: content
    content: libraries
    target: $SNAP/usr/lib/kbw
    default-provider: kbw

apps:
  ket:
    command: bin/python3 -m ket
    plugs:
      - home
    environment:
      LC_ALL: C.UTF-8
      LANG: C.UTF-8
      PATH: $SNAP/kbw:$PATH
      PYTHONPATH: $HOME/python-packages/lib/python3.8/site-packages
