name: Wheel

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  Windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - name: Checkout Submodules
        run: git submodule update --init --recursive
      - name: Compile Rust Libs
        run: |
          cargo build --release --manifest-path src\ket\clib\libs\libket\Cargo.toml
          cargo build --release --manifest-path src\ket\clib\libs\kbw\Cargo.toml
          copy src\ket\clib\libs\libket\target\release\ket.dll src\ket\clib\libs\ket.dll
          copy src\ket\clib\libs\kbw\target\release\kbw.dll src\ket\clib\libs\kbw.dll
          rmdir /s /q \ket\clib\libs\libket
          rmdir /s /q \ket\clib\libs\kbw
      - name: Install Python Dependencies
        run: py -m pip install wheel twine
      - name: Build wheel
        run: py setup.py bdist_wheel -p win-amd64
      - name: Archive wheel
        uses: actions/upload-artifact@v3
        with:
          name: win
          path: dist
      - name: Upload to PyPI
        env:
          TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
        run: py -m twine upload dist/*

  macOS:
    runs-on: macos-11

    steps:
      - uses: actions/checkout@v3
      - name: Checkout Submodules
        run: git submodule update --init --recursive
      - name: Compile Rust Libs
        run: |
          cargo build --release --manifest-path src/ket/clib/libs/libket/Cargo.toml
          cargo build --release --manifest-path src/ket/clib/libs/kbw/Cargo.toml
          mv src/ket/clib/libs/libket/target/release/libket.dylib src/ket/clib/libs/kbw/target/release/libkbw.dylib src/ket/clib/libs/
          rm -rf src/ket/clib/libs/libket/ src/ket/clib/libs/kbw/
      - name: Install Python Dependencies
        run: python -m pip install wheel twine
      - name: Build wheel
        run: python setup.py bdist_wheel -p macosx_10_7_x86_64
      - name: Archive wheel
        uses: actions/upload-artifact@v3
        with:
          name: macosx
          path: dist
      - name: Upload to PyPI
        env:
          TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
        run: python3 -m twine upload dist/*
